# Generated by Django 5.0.6 on 2024-07-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertype',
            name='name',
            field=models.CharField(choices=[('warehouse', 'Trabajador de Almacen'), ('delivery', 'Repartidor'), ('client', 'Cliente'), ('manager', 'Jefe de Logistica'), ('receptionist', 'Recepcionista')], max_length=25, unique=True),
        ),
    ]
