# Generated by Django 5.0.6 on 2024-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20240726_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workertype',
            name='name',
            field=models.CharField(choices=[('warehouse', 'Trabajador de Almacen'), ('delivery', 'Repartidor'), ('client', 'Cliente'), ('manager', 'Jefe de Logistica'), ('receptionist', 'Recepcionista')], default='client', max_length=25, unique=True),
        ),
    ]
