# Generated by Django 5.0.6 on 2024-06-22 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_solicitud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('tipo_paquete', models.CharField(max_length=20)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('distancia', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('agencia1', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('agencia2', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('agencia3', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
                ('agencia4', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(4)])),
            ],
        ),
    ]
