# Generated by Django 5.0.6 on 2024-06-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_solicitud', '0003_pedido_state_alter_tablaprecios_agencia1_and_more'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='login.cliente'),
        ),
    ]
