# Generated by Django 5.0.6 on 2024-07-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_solicitud', '0005_alter_tablaprecios_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
