# Generated by Django 5.0.6 on 2024-07-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_solicitud', '0007_remove_paquete_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
